doctrine:
    dbal:
        driver: 'pdo_mysql'
        #server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        resolve_target_entities:
            Pd\WidgetBundle\Entity\UserInterface: App\Entity\Account\User
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        second_level_cache:
            enabled: true
            log_enabled: true
            region_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool
            region_lifetime: 86400